# -*- coding: utf-8 -*-
"""heart_disease_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142Ag7fMuNQxWBg4CseWxf07Zi4iJGotk
"""

<pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

# 10️⃣ Pairplot pour visualiser des relations multiples
sns.pairplot(data[['age', 'trestbps', 'chol', 'thalach', y.columns[0]]], hue=y.columns[0], palette="husl")
plt.suptitle("Relations entre variables clés et la maladie cardiaque", y=1.02)
plt.show()

print("\n✅ Analyse graphique terminée.")